services:
  web:
    build: .
    ports:
      - 8080:8080 # 8080:5000 from 5000 in 8080
#      - "127.0.0.1:8080:8080" # 127.0.0.1:8080; or 8080:5000(if in docker 5000)
    command: python3 fitness.py #??????
    environment:
      DB_HOST: project_database
      RABBIT_HOST: rabbit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
#  redis:
#    image: "redis:alpine"

  celery_worker:
    build: .
    command: celery -A celery_worker worker --loglevel=INFO #--purge --pool=solo
    environment:
      smtp_sender: "<user_smtp_email>"
      smtp_password: "<user_smtp_password>"
      DB_HOST: project_database
      RABBIT_HOST: rabbit
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit

  db:
    image: "postgres"
    restart: "always"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    hostname: project_database

  rabbit_mq:
    image: "rabbitmq:3-management"
    ports:
      - 15672:15672
      - 5672:5672
    hostname: rabbit
#    environment:
#      RABBITMQ_DEFAULT_USER: rabbit
#      RABBITMQ_DEFAULT_PASS: rabbit